language: node_js
node_js: node
before_deploy:
  - npm run build
deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    branch: master
