language: node_js
node_js: node
before_deploy:
  - unset CI # https://github.com/facebook/create-react-app/issues/1150#issuecomment-267840717
  - npm run build
deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    branch: master
